### ISSUE TITLE
FAQ log limit of 100 entries

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#339] opened 2020-08-29 09:19 UTC
## Where to find the issue

https://www.coronawarn.app/en/faq/#exposure_check

## Describe the issue

In 1. of the FAQ entry [My exposure log shows checks for less than 14 days](https://www.coronawarn.app/en/faq/#exposure_check) it says:

"The log has a fixed limit of 100 entries. If there are more entries, only the latest are kept. We're in contact with Apple and Google so that the complete log will be displayed."

Android users have reported that the limit has been removed. See the closed issue [Exposure Checks only show 100 entries in the log (Android)](https://github.com/corona-warn-app/cwa-app-android/issues/941) https://github.com/corona-warn-app/cwa-app-android/issues/941 from @daimpi. @harambasicluka wrote in https://github.com/corona-warn-app/cwa-app-android/issues/941#issuecomment-674089365 that the issue had been brought up (presumably with Google and Apple), however we didn't hear about any feedback from the team. There is no mention of the issue in the [Google API for Exposure Notifications Release Notes](https://developers.google.com/android/exposure-notifications/release-notes) dated 2020-08-19.

## Suggested change
If the fixed limit of 100 entries has been reliably removed then the FAQ can be changed accordingly.

**Comment by mtb77** [comment] 2020-08-29 15:35
@MikeMcC399 thanks for reporting this. As far as I can see the limit has been changed for Android but iOS is still having this limit. 

I suggest to modify the FAQ entry from:

> The log has a fixed limit of 100 entries. If there are more entries, only the latest are kept. We're in contact with Apple and Google so that the complete log will be displayed.

to

> The log has a fixed limit of 100 entries on iOS Devices. If there are more entries, only the latest are kept. We're in contact with Apple so that the complete log will be displayed. The log limit of 100 entries on Android Devices has been recently removed by Google since ENF Version 16203302004.

@daimpi can you confirm the ENF version?

Thanks, 

Sascha
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2020-08-29 16:04
@mtb77 
Thank you for picking up this issue!

> I suggest to modify the FAQ entry to
> 
> > The log has a fixed limit of 100 entries on iOS Devices. If there are more entries, only the latest are kept. We're in contact with Apple so that the complete log will be displayed. The log limit of 100 entries on Android Devices has been recently removed by Google since ENF Version 16203302004.

I am running 16203302004 and can confirm that Export Exposure Checks is exporting 224 records. I can't say if this is the first version for which the restriction was removed.

I'm not sure if all readers are familiar with the abbreviation ENF. Possibly it is better to write out Exposure Notification Framework in full.
The Google documentation on https://developers.google.com/android/exposure-notifications/exposure-notifications-api in the menu of the left-hand side refers to the "Exposure Notification system". The Android UI (as opposed to the API) appears to be left undocumented on this site, so I don't really know the official name for the UI. Perhaps there is some other official Google documentation which refers to the term "Framework"?

**Comment by daimpi** [comment] 2020-08-29 16:23
Basically I can confirm the same as @MikeMcC399 did: 

I am running ENF 16203302004 on Android 9 and can confirm that Export Exposure Checks is exporting 221 records. I can't say for sure whether this is the first version for which the restriction was removed, but I'd guess so.

If the ENF version is brought up in the FAQ entry, I'd suggest also linking to the other FAQ entry where it is explained how users can find out their ENF version: https://www.coronawarn.app/en/faq/#ENF_version

**Comment by kereng5** [comment] 2020-08-29 16:52
I am running ENF 16203302004 since August 19 (100-record exposure log ist attached to issue #744), but there are more than 100 records in the Exposure Check log starting August 27.
So I doubt that ENF 16203302004 triggered the change.

**Comment by mtb77** [comment] 2020-08-30 07:22
Thanks for your comments - my updated sentence:

> The log has a fixed limit of 100 entries on iOS Devices. If there are more entries, only the latest are kept. We're in contact with Apple so that the complete log will be displayed. The log limit of 100 entries on Android Devices has been recently removed by Google since Exposure Notification Framework Version 16203302004. Please see https://www.coronawarn.app/en/faq/#ENF_version how to figure out the Version of the Framework installed.

> Diese Übersicht hat ein festes Limit von 100 Einträgen auf iOS Geräten. Wird dieses Limit überschritten, werden nur die neuesten Einträge behalten. Sie sehen dann typischerweise die Einträge von 7 Tagen. Wir sind mit Apple in Kontakt, damit die Übersicht in Zukunft vollständig angezeigt wird. Die Protokollgrenze von 100 Einträgen auf Android-Geräten wurde kürzlich von Google seit der Exposure Notification Framework Version 16203302004 aufgehoben. Bitte lesen Sie unter https://www.coronawarn.app/en/faq/#ENF_version nach, wie Sie die installierte Version des Frameworks herausfinden können.

Any further suggestions?

Thanks,

Sascha
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2020-08-30 10:31
@mtb77 
The texts look good to me. Thank you!
>The log has a fixed limit of 100 entries on iOS **D**evices. If there are more entries, only the latest are kept. We're in contact with Apple so that the complete log will be displayed. The log limit of 100 entries on Android **D**evices has been recently removed by Google since Exposure Notification Framework Version 16203302004. Please see https://www.coronawarn.app/en/faq/#ENF_version how to figure out the **V**ersion of the Framework installed.

The FAQ link in the German text should be https://www.coronawarn.app/de/faq/#ENF_version not https://www.coronawarn.app/en/faq/#ENF_version

Also, one very minor style comment:
I would not capitalise devices in "iOS **D**evices", nor version in "**V**ersion of the Framework".

**Comment by daimpi** [comment] 2020-08-30 11:25
According to @kereng5's [comment above](https://github.com/corona-warn-app/cwa-website/issues/339#issuecomment-683315149) it doesn't look like the ENF version change actually triggered the removal of the limit… it was probably just a configuration change pushed by Google at some point (such changes have seemingly no indicator via e.g. version number etc. cf. [here](https://github.com/corona-warn-app/cwa-app-android/issues/933#issuecomment-677463999)).

So you could drop the ENF version in the description and just state the time when the change was rolled out. Something like this:
> The log limit of 100 entries on Android Devices has been recently removed by Google ~~since Exposure Notification Framework Version 16203302004. Please see https://www.coronawarn.app/en/faq/#ENF_version how to figure out the Version of the Framework installed.~~ with a configuration change at the end of August 2020.

**Comment by MikeMcC399** [comment] 2020-08-30 11:44
@mtb77 
Is there any chance to get Google to comment about what they did,  how and when?
It seems that we are reverse engineering Google's changes! It would be good to really understand what is going on.

@daimpi said:
> According to @kereng5's [comment above](https://github.com/corona-warn-app/cwa-website/issues/339#issuecomment-683315149) it doesn't look like the ENF version change actually triggered the removal of the limit… it was probably just a configuration change pushed by Google at some point (such changes have seemingly no indicator via e.g. version number etc. cf. [here](https://github.com/corona-warn-app/cwa-app-android/issues/933#issuecomment-677463999)).

**Comment by mtb77** [comment] 2020-08-30 18:00
@MikeMcC399 Thanks for your feedback and also improving my non-native speaker English :) I could trigger a question to Google but to be honest, I would keep this channel open for important questions - I suggest to update just the FAQ entry.
To sum up, I would change the sentence to:

> The log has a fixed limit of 100 entries on iOS devices. If there are more entries, only the latest are kept. We're in contact with Apple so that the complete log will be displayed. The log limit of 100 entries on Android devices has been recently removed by Google with a configuration change at the end of August 2020.

If agreed, I will create a pull request and push the changes.

Cheers,

Sascha
Corona-Warn-App Open Source Team

**Comment by daimpi** [comment] 2020-08-30 18:39
sounds good to me 👍

**Comment by mtb77** [comment] 2020-08-30 19:40
Closing this issue in favor of the pull request #342 

Cheers,

Sascha
Corona-Warn-App Open Source Team

**Closed by mtb77** 2020-08-30 19:40 UTC
Labels: documentation
