### ISSUE TITLE
[svengbr] Server configuration recommendations

### ISSUE THREAD

**Issue by dannylinden** [corona-warn-app/cwa-website#60] opened 2020-06-16 05:36 UTC
I analyzed the Website with [Ryte](https://en.ryte.com/) and [Lighthouse from Google](https://developers.google.com/web/tools/lighthouse) and here some recommended changes on the Hosting Setup:

**404 Sites:**
Currently non-existing sites return a 403 error code instead of the correct one (404)

**Compression:**
The Server is currently not compressing Text-based resources (gzip, deflate or brotli). This reduces the loading-time espacially for mobile user.

---
Internal Tracking ID: [EXPOSUREAPP-8525](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8525)

**Comment by mojoaxel** [comment] 2020-07-02 18:03
> 404 Sites: Currently non-existing sites return a 403 error code instead of the correct one (404)

I can confirm this. A nice 404 page is shown but the server returns an 403 status code.

**Comment by dsarkar** [comment] 2020-12-11 15:18
Hi @mojoaxel @dannylinden, thanks for posting here. Seems fixed:

![image](https://user-images.githubusercontent.com/1409741/101920747-76f3fa00-3bcc-11eb-88cf-97a548cb0b33.png)

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2020-12-11 16:13
@dsarkar 
> Seems fixed

I don't think so.

1. Attempt to open a non-existent page in Google Chrome e.g. https://www.coronawarn.app/en/bad-page
2. Right-click and select Inspect > Network tab
3. re-load non-existent page
The returned status is 403 (forbidden) not 404 

![image](https://user-images.githubusercontent.com/66998419/101926606-af4b0680-3bd3-11eb-9367-e2c8b227be04.png)

**Comment by Ein-Tim** [comment] 2020-12-11 16:16
@dsarkar 

I don't think this is what @dannylinden means.

First of all it is about coronawarnapp.de and not about GitHub (the screenshot you posted is from the GitHub 404 Error Page).
Second, as @mojoaxel already said [here](https://github.com/corona-warn-app/cwa-website/issues/60#issuecomment-653148489) that there is a nice 404 Page, but the Server returns a 403 status code. 

Thanks for all your work! 
Have a nice evening!

**Comment by MikeMcC399** [comment] 2020-12-11 16:33
@Ein-Tim 
You recognized it was a Git-Hub 404 error page! Very good! 

Neither the original poster @dannylinden , nor @dsarkar said what URL they were using to test. It's always good to have repro steps to ensure everybody is talking about the same thing.

I tried out the same page using the test webserver on my local machine (the one which is started using npm start) and it returned the expected 404 error code. So it's a problem with the production web server of https://www.coronawarn.app/.

**Comment by dsarkar** [comment] 2020-12-12 11:47
Hi @mojoaxel, @dannylinden, @MikeMcC399.

Yes, you are right.  We will have a look at this. Thanks. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-07-21 07:34
@dsarkar 

It doesn't seem like anybody looked at this in the last months and there is still something wrong with the way that the production nginx server on https://www.coronawarn.app/ handles a 404 error. It displays a 404 custom error message and returns HTTP/1.1 403 forbidden.

This GitHub repository doesn't contain the setup information for the server, so it's not possible for an outsider to see what is causing the issue.

**Comment by dsarkar** [comment] 2021-07-21 07:43
@MikeMcC399 Yep, I will forward this issue to @svengabr and @mtb77.

**Comment by dsarkar** [comment] 2021-07-21 07:48
Internal Tracking ID: [EXPOSUREAPP-8525](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8525)

**Comment by Ein-Tim** [comment] 2022-04-15 16:49
This issue was not addressed for nearly 2 months. Although @svengabr was assigned to this issue & his name was added to the title, he never commented on this issue to let the community know whether the suggestions/recommendations mentioned in the OP will be implemented.

**Comment by svengabr** [comment] 2022-04-25 10:31
I once again asked the server administrators for an update in EXPOSUREAPP-8525

**Comment by MikeMcC399** [comment] 2022-05-13 08:01
@svengabr 

There still seems to be no text compression enabled.

If text compression could be enabled it should improve the performance. See https://docs.nginx.com/nginx/admin-guide/web-server/compression/ for documentation.

A Lighthouse report (available through Google Chrome F12) on https://www.coronawarn.app/en/faq/results/ shows significant potential savings:

![image](https://user-images.githubusercontent.com/66998419/168238318-4e0245f5-068d-47c8-a39c-87c22aa751bc.png)

**Comment by MikeMcC399** [comment] 2022-05-18 11:28
I guess there must be an organizational problem preventing the text compression setting, since there has been no feedback.

I tried it out on a test `nginx` server running under Ubuntu and after adding two lines to `/etc/nginx/conf.d/default.conf` it worked as expected:

```
   gzip on;
   gzip_types text/plain text/css application/javascript;
```

Probably on the production server that would need to be `text/javascript` instead.

**Comment by svengabr** [comment] 2022-05-18 11:42
@MikeMcC399 Yes unfortunately it's an organizational problem preventing the text compression setting. On my side, there is nothing I can do to speed this up as I have no control over the CDN or the webserver. 

However, I have once again pinged the responsible department and I am hoping for an update on this topic.

**Comment by MikeMcC399** [comment] 2022-05-24 07:23
@svengabr 
Do you have any Service Level Agreement for the CDN and webserver for support and configuration requests? Or is everything done on the basis of "best effort" with uncertain durations for requests?

**Comment by MikeMcC399** [comment] 2022-06-10 06:57
@svengabr 

Have you got any response from the responsible department about the text compression setting? If not, do you understand why you are not being supported?

**Comment by svengabr** [comment] 2022-06-13 10:38
@MikeMcC399 the hosting and maintenance are done by T-Systems and not by ourselves. I have once again escalated the issue and hoping for a response. Unfortunately, there is nothing further I can do on my side to speed this up rather than going 1 level higher in the hierarchy in every escalation.

**Comment by MikeMcC399** [comment] 2022-06-13 11:05
@svengabr 

Thank you for following through!

**Comment by MikeMcC399** [comment] 2022-07-05 06:53
@svengabr 

Should this issue be closed as https://github.com/corona-warn-app/cwa-website/labels/wontfix if TSI is unable to make the text compression configuration changes to the `nginx` webserver for https://www.coronawarn.app/?

**Comment by larswmh** [comment] 2022-07-14 12:00
This issue has now been solved. Accessing a non-existing page now returns a 404 error.

Closing this issue as completed.

**Closed by larswmh** 2022-07-14 12:00 UTC
Labels: mirrored-to-jira, technical-issue

**Comment by MikeMcC399** [comment] 2022-07-14 12:07
## 404 error

The repro steps in https://github.com/corona-warn-app/cwa-website/issues/60#issuecomment-743284779 now correctly return a 404 error.

![image](https://user-images.githubusercontent.com/66998419/178978639-ad39c598-99f0-4511-9633-e081ca8a2030.png)


## Text Compression

According to @larswmh in https://github.com/corona-warn-app/cwa-website/issues/25#issuecomment-1184358137

> We got feedback and received the information that compressing will not be implemented.

**Comment by dsarkar** [comment] 2022-07-22 13:58
added "won't fix" for the compression issue.
