### ISSUE TITLE
Phine numbers in footer cut off on mobile

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-website#58] opened 2020-06-15 22:10 UTC
## Where to find the issue
Footer of home page
https://photos.app.goo.gl/i6USG8N9QzhYTSw79

## Describe the issue
Phone numbers don't wrap and are therefore cut off on mobile screens.

**Comment by Lucurus** [comment] 2020-06-15 22:13
FYI, duplicate of #57

**Comment by SebastianWolf-SAP** [comment] 2020-06-15 22:18
Yep, this is a duplicate of #57.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-15 22:18 UTC
Labels: bug, duplicate

**Comment by corneliusroemer** [comment] 2020-06-15 22:22
Opened 1min before me 😅 is that error so young?

**Comment by Lucurus** [comment] 2020-06-15 22:37
Yeah, was only introduced with 57ffebd93cab03f9a405496ff1c78dd4c0cc7844 if I‘m not mistaken.

**Comment by corneliusroemer** [comment] 2020-06-15 22:43
@Lucurus You're right. I hope this is not how they built the app... Without proper tests before they go live. It's a work in progress it seems.

**Comment by Lucurus** [comment] 2020-06-15 22:50
@corneliusroemer I understand your concern but the development so far has been outstanding I would say, so I would forgive a small mistake like a misplaced telephone number, especially before launch day.

**Comment by SebastianWolf-SAP** [comment] 2020-06-15 22:50
@corneliusroemer Well, the app is open source. While you're obviously desperately waiting for the release, why not taking a look at the code and implement some tests if you miss some? ;)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
