### ISSUE TITLE
Is the FAQ entry `android_location` out of date?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2072] opened 2021-11-13 21:18 UTC
## Your Question

* Website URL Path: https://www.coronawarn.app/en/faq/
* Line / Paragraph: https://www.coronawarn.app/en/faq/#android_location
* Question: The FAQ entry `android_location` says: "If you are using Android 11 and the Corona-Warn-App version 1.5 or above, you don't have to allow location access in order to use the Corona-Warn-App. **This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App**."
Was this message meanwhile removed if one is using Android 11 or newer? 
I found the following related PR: https://github.com/corona-warn-app/cwa-app-android/pull/1057, but I was unsure how to interpret it.
If yes: Please let me know which version adjusted this & I would be happy to provide a PR for this.
If not: Will this be done soon? If not, this hint should probably be removed

**Comment by MikeMcC399** [comment] 2021-11-14 11:25
@Ein-Tim

There were quite a few different issues and PRs concerning this topic. The text that you refer to was put in place through issue #539 and PR #550 from @dsarkar.

The Android PR https://github.com/corona-warn-app/cwa-app-android/pull/1057 you quote made the change in CWA Android 1.5.0 released on Oct 19, 2020 to allow Exposure Logging to be activated on Android 11 without Location services being enabled. From that release onwards, the notification was no longer displayed if an attempt was made to enable Exposure Logging without Location services enabled, provided that enabled Location services was not needed for that step.

---

The statement "_This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App._" was partly based on my misunderstanding of what the information presented during onboarding was supposed to mean, which in turn was caused by some translation errors. The text shown during onboarding is informational only and it is not a notification as such.

Since CWA Android release 1.15.1, including up to the current version 2.13.2 the app displays the information documented in https://github.com/corona-warn-app/cwa-app-android/issues/2506#issuecomment-808126440

![Activate Location Setting EN DE 1 15 1](https://user-images.githubusercontent.com/66998419/112622295-24f97c00-8e2b-11eb-902f-fc21b6c1557d.png)

This information is always displayed, independently of what Android version is actually being used and independently of whether Location services is enabled or not. That is why I classify it as information dialog. A notification I would classify as something which was only presented depending on the state of the app or operating system.

That was quite a tough question because it was very complicated at the time and it was all changed many months ago!

## Summary

You can remove the sentence "This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App.".

The notification was already fixed in version 1.5.0.
What we thought was a notification was only information and the content of the information was corrected in version 1.15.1.

**Comment by Ein-Tim** [comment] 2021-11-14 12:37
@MikeMcC399 

Thank you for the long and detailed answer!

I will provide a PR for this which removed the sentence "This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App.", as you suggested! 

I will provide the PR by todays evening. 

Have a nice Sunday! 🙂

**Comment by Ein-Tim** [comment] 2021-11-14 16:06
PR #2073 created.

**Closed** 2021-11-14 18:15 UTC
Labels: question
