### ISSUE TITLE
ENError-Domain Fehler 5

### ISSUE THREAD

**Issue by JonasOelke** [corona-warn-app/cwa-website#143] opened 2020-06-30 17:34 UTC
I came across this error once and pressed „ok“, thought the app would work normal after restarting it. I did not look into it for a couple of days and noticed today the same error occurred again. In the meantime the risk detection did not work - last risk update was on 24/06/2020, I downloaded the app right at the release date and it worked until then. 

See the screenshot attached. 
![image](https://user-images.githubusercontent.com/48509640/86157784-2bf79600-bb08-11ea-8e9d-b0b8e5215308.png)

I am using an iPhone 7 running iOS 13.5.1
I am using version 1.0.2 (2)

For the app settings see the screenshot: 
![image](https://user-images.githubusercontent.com/48509640/86157965-6b25e700-bb08-11ea-87c7-87a11db695b5.png)

**Comment by n-thumann** [comment] 2020-07-01 07:15
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/766. Unfortunately, the issue is not solved yet ✌️

**Comment by tkowark** [comment] 2020-07-01 08:14
Yes, unfortunately not. Also, the website repository is just for issue related to the coronawarn.app website and not the apps.

**Closed by tkowark** 2020-07-01 08:14 UTC
