### ISSUE TITLE
FAQ serach is broken

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3550] opened 2023-07-02 17:13 UTC
## Where to find the issue
- https://coronawarn.app/de/faq
- https://coronawarn.app/en/faq

## Describe the issue
When searching on the FAQ page, the UI breaks:
<img width="1440" alt="Bildschirmfoto 2023-07-02 um 19 12 30" src="https://github.com/corona-warn-app/cwa-website/assets/67682506/4331ef14-a664-4d01-a9cb-63c8e78e2ce6">

## Suggested change
Fix the issue.

**Comment by MikeMcC399** [comment] 2023-07-03 06:22
@Ein-Tim 

The FAQ detail display https://coronawarn.app/en/faq is no longer working for a wide (desktop) browser window. The problem is not the search as such.

**Comment by MikeMcC399** [comment] 2023-07-03 06:27
The https://www.coronawarn.app/en/screenshots/ display is also broken.

**Comment by dsarkar** [comment] 2023-07-03 06:35
@Ein-Tim @MikeMcC399 Thanks, we will have a look at this.

**Comment by dsarkar** [comment] 2023-07-03 06:54
Issue is that the side notes also have an impact here:

<img width="496" alt="image" src="https://github.com/corona-warn-app/cwa-website/assets/1409741/1798502d-53c9-433e-a21f-0c0d1c1a5042">

will be fixed

**Closed** 2023-07-03 07:11 UTC
Labels: bug, technical-issue, science-blog

**Comment by MikeMcC399** [comment] 2023-07-03 08:38
How often do you deploy to production? The issue is not fixed there at the moment.

**Comment by larswmh** [comment] 2023-07-03 08:58
> How often do you deploy to production? The issue is not fixed there at the moment.

Deployments are still done for each commit to master, but we needed to purge the CDN. It should work now

**Comment by MikeMcC399** [comment] 2023-07-03 09:06
@larswmh 

I used Ctrl-F5 to refresh the browser and then I saw the correct display. It seems there was some caching causing a problem.
