### ISSUE TITLE
Screenshots: Rapid antigen test section out-of-date

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1257] opened 2021-05-12 10:11 UTC
## Where to find the issue

**"Rapid antigen test"**
https://www.coronawarn.app/en/screenshots/#android_rat
https://www.coronawarn.app/en/screenshots/#ios_rat

**"Schnelltest"**
https://www.coronawarn.app/de/screenshots/#android_rat
https://www.coronawarn.app/de/screenshots/#ios_rat

First reported for App version: 2.2
Reviewed as not fixed for App version: 2.25

## Describe the issue

The screenshots do not show the "Create Rapid Test Profile" or "Rapid Test Profile" tile in "Retrieve Test Result" underneath "Test with QR Code". The certificate tab and the Check In are also missing.

The published screenshots do not correspond to the UI in the current version of the app. They are taken from a much older version.

The website shows:

![image](https://user-images.githubusercontent.com/66998419/132577759-a7178ff0-91ca-48bb-9167-865e29ed18de.png)

Compare to more up-to-date screenshots in:
- https://www.coronawarn.app/en/screenshots/#android_rat_profiles
- https://www.coronawarn.app/en/screenshots/#ios_rat_profiles
- https://www.coronawarn.app/de/screenshots/#android_rat_profiles
- https://www.coronawarn.app/de/screenshots/#ios_rat_profiles

## Suggested change

- Replace the older screenshots with ones from the released version 

~~Possibly also:~~
~~- Add a screenshot of an example of Rapid Test Profile data entry screen and~~
~~- Add a screenshot of an example of a completed Rapid Test Profile showing a QR code~~
The above suggestions are implemented for instance in https://www.coronawarn.app/en/screenshots/#android_rat_profiles

Edit: Simplified the issue description.

It seems that the screenshots were captured by hand many versions ago and nothing has been updated since then.

**Comment by MikeMcC399** [comment] 2021-07-30 07:28
@dsarkar 

Also in the 2.6 screenshots the "Rapid antigen test" section screenshots are out-of-date and do not belong to this version.

![image](https://user-images.githubusercontent.com/66998419/127616761-2200e173-019e-44a3-bcb7-cea2c9192d6a.png)

In version 2.6 the title of the first tile is no longer "Register Your Test". It now says "Manage Your Tests". Also the menu bottom bar is missing the "Certificates" item.

In version 2.6 the title of the second tile is no longer "Retrieve Test Result". It now says "Manage Your Tests".

Possibly the other screenshots in this section are out-of-date too. They should be reviewed.

**Comment by MikeMcC399** [comment] 2021-09-06 16:24
This issue has not been fixed for the 2.8 Android screenshots in https://www.coronawarn.app/en/screenshots/#android_rat for instance.

The corresponding screenshots in en/screenshots/#android_rat for the upcoming 2.9 release in PR https://github.com/corona-warn-app/cwa-website/pull/1707 have also not been corrected.

**Comment by MikeMcC399** [comment] 2022-01-04 10:53
@dsarkar 

What is the significance of the "in review" label which was applied to this issue months ago?

The screenshots are still incorrect.

**Comment by MikeMcC399** [comment] 2022-01-17 10:11
The 2.16 screenshot for Rapid Antigen Test continue to be out of date.

**Comment by ahodzic2** [comment] 2022-03-17 21:39
@MikeMcC399 

Does this continue to be an issue as of 2.19? Interested in helping to correct the issue if so.

**Comment by MikeMcC399** [comment] 2022-03-18 06:34
@ahodzic2 

> Does this continue to be an issue as of 2.19? Interested in helping to correct the issue if so.

I have always assumed that the app developers would need to provide updated screenshots. I am not a developer in the Open Source Team, so this is why the issue is still open.

Are you part of the Open Source Development Team? Are you in a position to provide a full replacement set of screenshots for Android / iOS / English / German? There are 40 images involved.

**Comment by Ein-Tim** [comment] 2022-04-15 16:11
Still a valid issue, which has not been addressed in over a year. IMO the problem is that it seems like not for every new release screenshots are provided. See https://github.com/corona-warn-app/cwa-website/issues/1760#issuecomment-1100198898.

**Closed** 2023-01-02 15:25 UTC
Labels: bug, screenshots
